#!/bin/bash


for i in {1..10}
do
        sudo docker service create --replicas 5 --name redis --update-delay 15s redis:3.0.7
	echo "$i Round........" >>5redis.txt
        sudo docker service ps --format "{{.Node}}: {{.CurrentState}}" redis >> 5redis.txt
        sudo docker service rm redis
done

