#!/bin/bash

for i in {1..10}
do
        sudo docker service create --replicas 7 --name redis --update-delay 15s redis:3.0.7
        echo "$i Round........" >>7redis.txt
        sudo docker service ps --format "{{.Node}}: {{.CurrentState}}" redis >> 7redis.txt
        sudo docker service rm redis
done

